version: "3.7"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566" # logs
      - "4568:4568" # kinesis
      - "4574:4574" # lambda
    environment:
      - PORT_WEB_UI=9000
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=kinesis,lambda
    volumes:
      - ./consumer:/consumer
      - ./producer:/producer
      - localstack-volume:/tmp/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  localstack-volume:
