version: "3.7"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - PORT_WEB_UI=9000
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TMPDIR=/private$TMPDIR
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=kinesis,lambda,s3,firehose
    volumes:
      - ./consumer:/consumer
      - ./producer:/producer
      - localstack-volume:/tmp/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock
  terraform:
    image: hashicorp/terraform:0.14.11
    volumes:
      - ./stacks:/stacks
    working_dir: /stacks
volumes:
  localstack-volume:
